config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root to: 'devise/sessions#new'
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end

  resources :products

  resources :reports do
    collection do
      get :download
      get :download_report
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resources)
    reports_path
  end

  def after_sign_out_path_for(resources)
    new_user_session_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :release_year, :price, :description, :imdb_id, :poster_url)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end


  def download_report
    @reports = Report.all

  end

  def download
    @reports = Report.all
    #@reports =  Report.where('from_date > ?', DateTime.now)
    respond_to do |format|
      format.xlsx
    end
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:amount, :from_date, :to_date, :investment, :fund)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/_flash_messages.html.erb
<%= content_tag 'p', (flash[:notice] || flash[:success]).html_safe, class: 'alert alert-success alert-dismissible' if flash[:notice] || flash[:success] %>
<%= content_tag 'p', (flash[:error] || flash[:alert]).html_safe, class: 'alert alert-danger alert-dismissible' if flash[:error] || flash[:alert] %>
<% flash.clear if(request.path.split("/").last != "thank-you") %>

app/views/layouts/_footer.html.erb
<div class="footer">
	<p>RubyOnRails@2019</p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  	<div class="container-fluid">
		<div class="navbar-header">
	  		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
	  		</button>
	  		<%= link_to root_path, class: 'navbar-brand' do %>
				Investment Info
	  		<% end %>
		</div>
		<div class="collapse navbar-collapse" id="myNavbar">
	  		<ul class="nav navbar-nav navbar-right">
	  			<% if user_signed_in? %>
					<li>
						<%= link_to logout_path, method: :delete do %>
		  					<span class="glyphicon glyphicon-off"> </span>
		  					Sign Out
						<% end %>
					</li>
	  			<% else %>
	  				<li>
						<%= link_to new_user_session_path do %>
			  				<span class="glyphicon glyphicon-log-in"> </span> Sign In
						<% end %>
					</li>
	  			<% end %>
	  		</ul>
		</div>
  	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Product Details</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <div class="wrapper">
      <div class="container">
        <%= render partial: 'layouts/flash_messages' %>
        <%= yield %>
      </div>
    <div class="push"></div>
    </div>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :release_year %>
    <%= form.number_field :release_year %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :imdb_id %>
    <%= form.text_field :imdb_id %>
  </div>

  <div class="field">
    <%= form.label :poster_url %>
    <%= form.text_field :poster_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Release year</th>
      <th>Price</th>
      <th>Description</th>
      <th>Imdb</th>
      <th>Poster url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.release_year %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td><%= product.imdb_id %></td>
        <td><%= product.poster_url %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Release year:</strong>
  <%= @product.release_year %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Imdb:</strong>
  <%= @product.imdb_id %>
</p>

<p>
  <strong>Poster url:</strong>
  <%= @product.poster_url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
<%#= link_to "Export report as spreadsheet", download_reports_path(from_date:"10 November 2019",format: "xlsx"), class: "btn btn-danger" %>

  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= form.label :from_date %>
    <%= form.datetime_select :from_date %>
  </div>

  <!--<div class="field">-->
    <!--<%= form.label :to_date %>-->
    <!--<%= form.datetime_select :to_date %>-->
      <!--</div>-->

    <div class="field">
      <%= form.label :investment_fund %>
      <%= form.select :investment, ["Axis Long Term Equity Fund","HDFC Long Term Equity Fund","Short Term Equity Fund"]%>
      <%#= form.text_field :investment %>
    </div>

    <div class="field">
      <%= form.label :amount %>
      <%= form.number_field :amount %>
    </div>



  <div class="actions">
    <%= form.submit "clear", :type => "reset" %>
  </div>
<% end %>

app/views/reports/download_report.erb
      <%= form_tag download_reports_path(format: "xlsx"), :method => 'get', class: "form-inline"  do %>
          Investment Type :  <%= select_tag "book", options_for_select(["Axis Long Term Equity Fund","HDFC Long Term Equity Fund","Short Term Equity Fund"]) %>
          <br><br>
          Select Date : <%= date_field_tag :from_date, params[:from_date], class: "form-control mb-2 mr-sm-2"%>
          <%= submit_tag "Download Nav History", class: 'btn btn-primary mb-2' %>
      <%end%>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table class="table">
  <thead class="thead-dark">
  <tr>
    <th>Amount</th>
    <th>From date</th>
    <th>To date</th>
    <th>Investment</th>
    <th>Fund</th>
    <th>View Report</th>
  </tr>
  </thead>
  <% @reports.each do |report| %>
      <tr>
        <td><%= report.amount %></td>
        <td><%= report.from_date %></td>
        <td><%= report.to_date %></td>
        <td><%= report.investment %></td>
        <td><%= report.fund %></td>

        <td><%= link_to "view", report_path(report), class:'btn btn-block btn-warning'%></td>
              </tr>
          <% end %>
        <tr>

          <td>
            <%= link_to 'New Report', new_report_path ,class: 'btn btn-block btn-warning'%>
          </td>

          <td>

            <%= link_to 'Download Report', download_report_reports_path ,class: 'btn btn-block btn-warning'%>
          </td>
        </tr>


</table>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @report.amount %>
</p>

<p>
  <strong>From date:</strong>
  <%= @report.from_date %>
</p>

<p>
  <strong>To date:</strong>
  <%= @report.to_date %>
</p>

<p>
  <strong>Investment:</strong>
  <%= @report.investment %>
</p>

<p>
  <strong>Fund:</strong>
  <%= @report.fund %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>